import { Inject, Injectable } from '@nestjs/common';
import { VideoAgeRecommendationAdapter } from '@tlc/content/core/adapter/video-recommendation.adapter.interface';
import { VideoSummaryGenerationAdapter } from '@tlc/content/core/adapter/video-summary-generator.adapter.interface';
import { VideoTranscriptGenerationAdapter } from '@tlc/content/core/adapter/video-transcript-generator.adapter.interface';
import { VideoMetadataService } from '@tlc/content/core/service/video-metadata.service';
import { VideoMetadata } from '@tlc/content/persistence/entity/video-metadata.entity';
import { Video } from '@tlc/content/persistence/entity/video.entity';

@Injectable()
export class VideoProcessorService {
  constructor(
    private readonly videoMetadataProvider: VideoMetadataService,
    @Inject(VideoSummaryGenerationAdapter)
    private readonly videoSummaryGenerator: VideoSummaryGenerationAdapter,
    @Inject(VideoTranscriptGenerationAdapter)
    private readonly videoTranscriptGenerator: VideoTranscriptGenerationAdapter,
    @Inject(VideoAgeRecommendationAdapter)
    private readonly videoAgeRecommendationAdapter: VideoAgeRecommendationAdapter
  ) {}

  async processMetadataAndModeration(video: Video) {
    const summary = await this.videoSummaryGenerator.generateSummary(video.url);
    const transcript = await this.videoTranscriptGenerator.generateTranscript(video.url);
    const ageRecommendation =
      await this.videoAgeRecommendationAdapter.getAgeRecommendation(video.url);
    video.metadata = new VideoMetadata({
      autoGeneratedDescription: summary,
      transcript,
      ageRating: ageRecommendation?.ageRating,
      ageRatingExplanation: ageRecommendation?.explanation,
      ageRatingCategories: ageRecommendation?.categories,
    });

    await this.videoMetadataProvider.setVideoDuration(video);
  }
}
