import { Video } from './video.entity';
import { DefaultEntity } from '@tlc/shared-module/typeorm/entity/default.entity';
import { Column, Entity, JoinColumn, OneToOne, VersionColumn } from 'typeorm';

@Entity({ name: 'VideoMetadata' })
export class VideoMetadata extends DefaultEntity<VideoMetadata> {
  @Column({ type: 'text', nullable: true })
  autoGeneratedDescription: string | null;

  @Column({ type: 'text', nullable: true })
  transcript: string | null;

  @Column({ type: 'integer', nullable: true })
  ageRating: number | null;

  @Column({ type: 'text', nullable: true })
  ageRatingExplanation: string | null;

  @Column('text', { nullable: true, array: true })
  ageRatingCategories: string[] | null;

  @OneToOne(() => Video, (video) => video.metadata)
  @JoinColumn({
    name: 'videoId',
    referencedColumnName: 'id',
  })
  video: Video;

  @Column({ type: 'uuid', nullable: false })
  videoId: string;

  @VersionColumn()
  version: number;
}
