import { Video } from '@tlc/content/persistence/entity/video.entity';
import { DefaultEntity } from '@tlc/shared-module/typeorm/entity/default.entity';
import { Column, Entity, OneToOne } from 'typeorm';

@Entity({ name: 'VideoMetadata' })
export class VideoMetadata extends DefaultEntity<VideoMetadata> {
  @Column({ type: 'text', nullable: true })
  autoGeneratedDescription: string | null;

  @Column({ type: 'text' })
  transcript: string | null;

  @Column({ type: 'integer', nullable: true })
  ageRating: number | null;

  @Column({ type: 'text', nullable: true })
  ageRatingExplanation: string | null;

  @Column('text', { nullable: true, array: true })
  ageRatingCategories: string[] | null;

  @OneToOne(() => Video, (video) => video.metadata)
  video: Video;
}
