import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1761348887704 implements MigrationInterface {
    name = 'Migration1761348887704'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Thumbnail" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "url" character varying NOT NULL, CONSTRAINT "PK_29cfea45a44edc72c599d42037f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "VideoMetadata" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "autoGeneratedDescription" text, "transcript" text, "ageRating" integer, "ageRatingExplanation" text, "ageRatingCategories" text array, "videoId" uuid NOT NULL, "version" integer NOT NULL, CONSTRAINT "REL_678d67fbd94f3a4f4c57a0507b" UNIQUE ("videoId"), CONSTRAINT "PK_67db734088f52ed6ffea3346abf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Video" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "url" character varying NOT NULL, "sizeInKb" bigint, "duration" bigint, "movieId" uuid, "episodeId" uuid, CONSTRAINT "REL_46efd1060cb7a7c545b06120d1" UNIQUE ("movieId"), CONSTRAINT "REL_ce049b6bf5d3e5aee0f3dbd8dc" UNIQUE ("episodeId"), CONSTRAINT "PK_2a23c3da7a2fc570b1696191b87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."Content_type_enum" AS ENUM('MOVIE', 'TV_SHOW')`);
        await queryRunner.query(`CREATE TABLE "Content" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "type" "public"."Content_type_enum" NOT NULL, "title" character varying NOT NULL, "description" character varying NOT NULL, "ageRecommendation" integer, "releaseDate" date, "externalRating" double precision, "thumbnailId" uuid, CONSTRAINT "REL_9eb0969c366defe748854d453a" UNIQUE ("thumbnailId"), CONSTRAINT "PK_7cb78a77f6c66cb6ea6f4316a5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_318d7f4cb6dd2218ccf69b0941" ON "Content" ("type") `);
        await queryRunner.query(`CREATE TABLE "Episode" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "title" character varying NOT NULL, "description" character varying NOT NULL, "season" integer NOT NULL, "number" integer NOT NULL, "tvShowId" uuid NOT NULL, "thumbnailId" uuid, CONSTRAINT "REL_7153938ad76137550256fd3b40" UNIQUE ("thumbnailId"), CONSTRAINT "PK_c61e604db606b512a70c676a5f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "VideoMetadata" ADD CONSTRAINT "FK_678d67fbd94f3a4f4c57a0507b0" FOREIGN KEY ("videoId") REFERENCES "Video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Video" ADD CONSTRAINT "FK_46efd1060cb7a7c545b06120d14" FOREIGN KEY ("movieId") REFERENCES "Content"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Video" ADD CONSTRAINT "FK_ce049b6bf5d3e5aee0f3dbd8dc0" FOREIGN KEY ("episodeId") REFERENCES "Episode"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Content" ADD CONSTRAINT "FK_9eb0969c366defe748854d453a6" FOREIGN KEY ("thumbnailId") REFERENCES "Thumbnail"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Episode" ADD CONSTRAINT "FK_3dc5f16eddbe518eff23f510ec6" FOREIGN KEY ("tvShowId") REFERENCES "Content"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Episode" ADD CONSTRAINT "FK_7153938ad76137550256fd3b40a" FOREIGN KEY ("thumbnailId") REFERENCES "Thumbnail"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Episode" DROP CONSTRAINT "FK_7153938ad76137550256fd3b40a"`);
        await queryRunner.query(`ALTER TABLE "Episode" DROP CONSTRAINT "FK_3dc5f16eddbe518eff23f510ec6"`);
        await queryRunner.query(`ALTER TABLE "Content" DROP CONSTRAINT "FK_9eb0969c366defe748854d453a6"`);
        await queryRunner.query(`ALTER TABLE "Video" DROP CONSTRAINT "FK_ce049b6bf5d3e5aee0f3dbd8dc0"`);
        await queryRunner.query(`ALTER TABLE "Video" DROP CONSTRAINT "FK_46efd1060cb7a7c545b06120d14"`);
        await queryRunner.query(`ALTER TABLE "VideoMetadata" DROP CONSTRAINT "FK_678d67fbd94f3a4f4c57a0507b0"`);
        await queryRunner.query(`DROP TABLE "Episode"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_318d7f4cb6dd2218ccf69b0941"`);
        await queryRunner.query(`DROP TABLE "Content"`);
        await queryRunner.query(`DROP TYPE "public"."Content_type_enum"`);
        await queryRunner.query(`DROP TABLE "Video"`);
        await queryRunner.query(`DROP TABLE "VideoMetadata"`);
        await queryRunner.query(`DROP TABLE "Thumbnail"`);
    }

}
