import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1745272447269 implements MigrationInterface {
    name = 'Migration1745272447269'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "VideoMetadata" ALTER COLUMN "autoGeneratedDescription" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "VideoMetadata" ALTER COLUMN "transcript" DROP NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "VideoMetadata" ALTER COLUMN "transcript" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "VideoMetadata" ALTER COLUMN "autoGeneratedDescription" SET NOT NULL`);
    }

}
