import { INestApplication } from '@nestjs/common';
import { TestingModule } from '@nestjs/testing';
import { createNestApp } from '@tlc/shared-lib/test';
import { ConfigModule, ConfigService } from '@tlc/shared-module/config';
import knex, { Knex } from 'knex';
import nock, { cleanAll } from 'nock';
import { movieFactory } from '../../../../../__test__/factory/movie.factory';
import { videoMetadataFactory } from '../../../../../__test__/factory/video-metadata.factory';
import { videoFactory } from '../../../../../__test__/factory/video.factory';
import { cleanUpContentDatabase } from '../../../../../__test__/helper/content-db.test-helper';
import { CONTENT_TEST_FIXTURES } from '../../../../../admin/__test__/e2e/contants';
import { ContentConfig, contentConfigFactory } from '../../../../../config';
import { Video } from '../../../../../shared/persistence/entity/video.entity';
import { ContentVideoProcessorModule } from '../../../../content-video-processor.module';
import { GenerateSummaryForVideoUseCase } from '../../generate-summary-for-video.use-case';

describe('GenerateSummaryForVideoUseCase', () => {
  let module: TestingModule;
  let app: INestApplication;
  let testDbClient: Knex;
  let generateSummaryForVideoUseCase: GenerateSummaryForVideoUseCase;

  beforeAll(async () => {
    const nestTestSetup = await createNestApp([
      ConfigModule.forRoot({
        load: [contentConfigFactory],
      }),
      ContentVideoProcessorModule,
    ]);
    app = nestTestSetup.app;
    module = nestTestSetup.module;
    const configService = module.get<ConfigService<ContentConfig>>(ConfigService);
    generateSummaryForVideoUseCase = module.get<GenerateSummaryForVideoUseCase>(
      GenerateSummaryForVideoUseCase
    );

    testDbClient = knex({
      client: 'pg',
      connection: `${configService.get('content.database.url')}`,
      searchPath: ['public'],
    });
  });

  afterEach(async () => {
    await cleanUpContentDatabase(testDbClient);

    cleanAll();
    jest.restoreAllMocks();
  });

  afterAll(async () => {
    //TODO move it to be shared
    await app.close();
    await module.close();
  });

  it('generates a summary for a video with existing metadata', async () => {
    const movieContent = movieFactory.build();
    const video = videoFactory.build({
      url: `${CONTENT_TEST_FIXTURES}/sample.mp4`,
    });
    const videoMetadata = videoMetadataFactory.build({
      videoId: video.id,
    });
    await testDbClient('Content').insert(movieContent);
    await testDbClient('Video').insert(video);
    await testDbClient('VideoMetadata').insert(videoMetadata);

    nock('https://generativelanguage.googleapis.com')
      .post('/v1beta/models/gemini-2.0-flash:generateContent')
      .query(true) // Match any query parameters
      .reply(200, {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: JSON.stringify({
                    responseText: 'This is a test video summary.',
                  }),
                },
              ],
            },
            finishReason: 'STOP',
            index: 0,
          },
        ],
      });

    const videoEntity = new Video(video);

    await generateSummaryForVideoUseCase.generateSummary(videoEntity);
    const updatedVideoMetadata = await testDbClient('VideoMetadata')
      .where({ videoId: video.id })
      .first();
    expect(updatedVideoMetadata).toBeDefined();
    expect(updatedVideoMetadata.autoGeneratedDescription).toEqual(
      'This is a test video summary.'
    );
  });

  it('creates new metadata when no metadata exists for the video', async () => {
    // Create content without metadata
    const movieContent = movieFactory.build();
    const video = videoFactory.build({
      url: `${CONTENT_TEST_FIXTURES}/sample.mp4`,
    });
    await testDbClient('Content').insert(movieContent);
    await testDbClient('Video').insert(video);

    nock('https://generativelanguage.googleapis.com')
      .post('/v1beta/models/gemini-2.0-flash:generateContent')
      .query(true)
      .reply(200, {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: JSON.stringify({
                    responseText: 'New video summary for content without metadata.',
                  }),
                },
              ],
            },
            finishReason: 'STOP',
            index: 0,
          },
        ],
      });

    const videoEntity = new Video(video);

    await generateSummaryForVideoUseCase.generateSummary(videoEntity);

    // Verify a new metadata record was created
    const newMetadata = await testDbClient('VideoMetadata')
      .where({ videoId: video.id })
      .first();

    expect(newMetadata).toBeDefined();
    expect(newMetadata.autoGeneratedDescription).toEqual(
      'New video summary for content without metadata.'
    );
  });

  it('handles API errors during summary generation', async () => {
    const movieContent = movieFactory.build();
    const video = videoFactory.build({
      url: `${CONTENT_TEST_FIXTURES}/sample.mp4`,
    });
    await testDbClient('Content').insert(movieContent);
    await testDbClient('Video').insert(video);

    // Mock the API to throw an error
    nock('https://generativelanguage.googleapis.com')
      .post('/v1beta/models/gemini-2.0-flash:generateContent')
      .query(true)
      .replyWithError('API connection error');

    const videoEntity = new Video(video);

    await expect(
      generateSummaryForVideoUseCase.generateSummary(videoEntity)
    ).rejects.toThrow();
  });
});
