name: Deploy Billing Api

on:
  push:
    tags:
      - 'billing-*' # Essa action só executa quando uma tag com prefixo 'billing-' for criada

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t billing-api:latest --build-arg APP_COMMAND="node dist/app/monolith/main.js" --build-arg APP_NAME=billing-api .
          echo "GITHUB_REF: $GITHUB_REF"
          echo "Extracted tag: ${GITHUB_REF#refs/tags/}"
          docker tag billing-api:latest billing-api:${GITHUB_REF#refs/tags/}
