name: Release Nx Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string
      app:
        description: 'Select the app to release'
        required: true
        type: choice
        options:
          - billing-api
          - monolith
          - another-app

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all git history and tags
        run: git fetch --prune --unshallow --tags
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Nx release changelog
        run: |
          echo "Running: nx release changelog ${{ github.event.inputs.version }} -p ${{ github.event.inputs.app }}"
          npx nx release changelog ${{ github.event.inputs.version }} -p ${{ github.event.inputs.app }} --dry-run=true
